 --DROP DATABASE QL_CUAHANGDTDD
--TAO DATABASE
CREATE DATABASE QL_CUAHANGDTDD
GO
--SU DUNG DATABASE
USE QL_CUAHANGDTDD
GO
--BANG SAN PHAM
CREATE TABLE SANPHAM
(
	ID_SANPHAM INT PRIMARY KEY
	,TEN_SANPHAM NVARCHAR(50)
	,DVT NVARCHAR(50)
	,DONGIA INT
	,TONKHO INT
)
GO
--BANG KHACH HANG
CREATE TABLE KHACHHANG
(
	ID_KHACHHANG INT PRIMARY KEY
	,TEN_KHACHHANG NVARCHAR(50)
	,DIACHI NVARCHAR(50)
	,SDT NVARCHAR(50)
)
GO
--BANG NGUOI DUNG
CREATE TABLE NGUOIDUNG
(
	ID_NGUOIDUNG INT PRIMARY KEY
	,TEN_NGUOIDUNG NVARCHAR(50)
	,DIACHI NVARCHAR(50)
	,SDT NVARCHAR(50)
	,TAIKHOAN NVARCHAR(50) UNIQUE
	,MATKHAU NVARCHAR(50)
	,IS_ADMINISTRATOR BIT
)
GO
--BANG PHIEU NHAP
CREATE TABLE PHIEUNHAPKHO
(
	ID_PHIEUNHAPKHO INT PRIMARY KEY
	,NGAYNHAP DATE
)
GO
--BANG CHI TIET PHIEU NHAP
CREATE TABLE CTPN
(
	ID_CTPN INT PRIMARY KEY
	,ID_PHIEUNHAPKHO INT CONSTRAINT FK_PHIEUNHAP_CTPN FOREIGN KEY REFERENCES PHIEUNHAPKHO(ID_PHIEUNHAPKHO)
	,ID_SANPHAM INT CONSTRAINT FK_CTPN_SANPHAM FOREIGN KEY REFERENCES SANPHAM(ID_SANPHAM)
	,SL INT
)
GO
--BANG PHIEU XUAT
CREATE TABLE PHIEUXUATKHO
(
	ID_PHIEUXUATKHO INT PRIMARY KEY
	,NGAYXUAT DATE
)
GO
--BANG CHI TIET PHIEU XUAT
CREATE TABLE CTPX
(
	ID_CTPX INT PRIMARY KEY
	,ID_PHIEUXUATKHO INT CONSTRAINT FK_PHIEUXUAT_CTPX FOREIGN KEY REFERENCES PHIEUXUATKHO(ID_PHIEUXUATKHO)
	,ID_SANPHAM INT CONSTRAINT FK_CTPX_SANPHAM FOREIGN KEY REFERENCES SANPHAM(ID_SANPHAM)
	,SL INT
)
GO
--BANG HOA DON
CREATE TABLE HOADON
(
	ID_HOADON INT PRIMARY KEY
	,ID_KHACHHANG INT CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY REFERENCES KHACHHANG(ID_KHACHHANG)
	,NGAYMUA DATE
)
GO
--BANG CHI TIET HOA DON
CREATE TABLE CTHD
(
	ID_CTHD INT PRIMARY KEY
	,ID_HOADON INT CONSTRAINT FK_HOADON_CTHD FOREIGN KEY REFERENCES HOADON(ID_HOADON)
	,ID_SANPHAM INT CONSTRAINT FK_CTHD_SANPHAM FOREIGN KEY REFERENCES SANPHAM(ID_SANPHAM)
	,SL INT
)
GO
--PROCEDUCED


--SP
--THEM SP
CREATE PROC SP_THEMSANPHAM(@ID_SANPHAM INT, @TEN_SANPHAM NVARCHAR(50),@DVT NVARCHAR(50),@DONGIA INT,@TONKHO INT)
AS
BEGIN
	INSERT INTO SANPHAM(ID_SANPHAM, TEN_SANPHAM, DVT, DONGIA, TONKHO) VALUES(@ID_SANPHAM, @TEN_SANPHAM, @DVT, @DONGIA, @TONKHO)
END
GO
--DSSP
CREATE PROC SP_DSSP
AS
BEGIN
	SELECT * FROM SANPHAM
END
GO
--XOA SP
CREATE PROC SP_XOASANPHAM(@ID_SANPHAM INT)
AS
BEGIN
	DELETE FROM SANPHAM
	WHERE ID_SANPHAM = @ID_SANPHAM
END
GO
--SUA SP
CREATE PROC SP_SUASANPHAM(@ID_SANPHAM INT, @TEN_SANPHAM NVARCHAR(50), @DVT NVARCHAR(50), @DONGIA INT,@TONKHO INT)
AS
BEGIN
	UPDATE SANPHAM
	SET TEN_SANPHAM = @TEN_SANPHAM, DVT = @DVT, DONGIA = @DONGIA, TONKHO = @TONKHO
	WHERE ID_SANPHAM = @ID_SANPHAM
END
GO
--KH
--THEM KHACH HANG
CREATE PROC SP_THEMKHACHHANG(@ID_KHACHHANG INT, @TENKHACHHANG NVARCHAR(50), @DIACHI NVARCHAR(50), @SDT NVARCHAR(50))
AS
BEGIN
	INSERT INTO KHACHHANG(ID_KHACHHANG, TEN_KHACHHANG, DIACHI, SDT) VALUES(@ID_KHACHHANG, @TENKHACHHANG, @DIACHI, @SDT)
END
GO
--DSKH
CREATE PROC SP_DSKH
AS
BEGIN
	SELECT * FROM KHACHHANG
END
GO
--XOA KHACH HANG
CREATE PROC SP_XOAKHACHHANG(@ID_KHACHHANG INT)
AS
BEGIN
	DELETE KHACHHANG WHERE ID_KHACHHANG = @ID_KHACHHANG
END
GO
--SUA KHACH HANG
CREATE PROC SP_SUAKHACHHANG(@ID_KHACHHANG INT, @TENKHACHHANG NVARCHAR(50), @DIACHI NVARCHAR(50), @SDT NVARCHAR(50))
AS
BEGIN
	UPDATE KHACHHANG
	SET TEN_KHACHHANG = @TENKHACHHANG, DIACHI = @DIACHI, SDT = @SDT
	WHERE ID_KHACHHANG = @ID_KHACHHANG
END
GO
--TIM KHACHHANG
CREATE PROC SP_TIMKHACHHANG(@TENKHACHHANG NVARCHAR(50))
AS
BEGIN
	SELECT * FROM KHACHHANG
	WHERE TEN_KHACHHANG = @TENKHACHHANG
END
GO
--PN
--THEM PHIEU NHAP
CREATE PROC SP_THEMPHIEUNHAP(@ID_PHIEUNHAP INT, @NGAYNHAP DATE)
AS
BEGIN
	INSERT INTO PHIEUNHAPKHO(ID_PHIEUNHAPKHO, NGAYNHAP) VALUES(@ID_PHIEUNHAP, @NGAYNHAP)
END
GO
--DSPN
CREATE PROC SP_DSPN
AS
BEGIN
	SELECT * FROM PHIEUNHAPKHO
END
GO
--XOA PHIEU NHAP
CREATE PROC SP_XOAPHIEUNHAP(@ID_PHIEUNHAP INT)
AS
BEGIN
	DELETE PHIEUNHAPKHO
	WHERE ID_PHIEUNHAPKHO = @ID_PHIEUNHAP
END
GO
--SUA PHIEU NHAP
CREATE PROC SP_SUAPHIEUNHAP(@ID_PHIEUNHAP INT, @NGAYNHAP DATE)
AS
BEGIN
	UPDATE PHIEUNHAPKHO
	SET NGAYNHAP = @NGAYNHAP
	WHERE ID_PHIEUNHAPKHO = @ID_PHIEUNHAP
END
GO

--CTPN
--THEM CHI TIET PHIEU NHAP
CREATE PROC SP_THEMCTPN(@ID_CTPN INT,@ID_PHIEUNHAPKHO INT ,@ID_SANPHAM INT, @SL INT)
AS
BEGIN
	INSERT INTO CTPN(ID_CTPN,ID_PHIEUNHAPKHO ,ID_SANPHAM, SL) VALUES(@ID_CTPN,@ID_PHIEUNHAPKHO ,@ID_SANPHAM, @SL)
END
GO
--DSCTPN
CREATE PROC SP_DSCTPN
AS
BEGIN
	SELECT * FROM CTPN
END
GO
--XOA CTPN
CREATE PROC SP_XOACTPN(@ID_CTPN INT)
AS
BEGIN
	DELETE CTPN
	WHERE ID_CTPN = @ID_CTPN
END
GO
--SUA CTPN
CREATE PROC SP_SUACTPN(@ID_CTPN INT ,@ID_SANPHAM INT, @SL INT)
AS
BEGIN
	UPDATE CTPN
	SET ID_SANPHAM = @ID_SANPHAM, SL = @SL
	WHERE ID_CTPN = @ID_CTPN
END
GO

--PX
--THEM PHIEU XUAT
CREATE PROC SP_THEMPHIEUXUAT(@ID_PHIEUXUAT INT, @NGAYXUAT DATE)
AS
BEGIN
	INSERT INTO PHIEUXUATKHO(ID_PHIEUXUATKHO, NGAYXUAT) VALUES(@ID_PHIEUXUAT, @NGAYXUAT)
END
GO
--DSPX
CREATE PROC SP_DSPX
AS
BEGIN
	SELECT * FROM PHIEUXUATKHO
END
GO
--XOA PHIEU XUAT
CREATE PROC SP_XOAPHIEUXUAT(@ID_PHIEUXUATKHO INT)
AS
BEGIN
	DELETE PHIEUXUATKHO
	WHERE ID_PHIEUXUATKHO = @ID_PHIEUXUATKHO
END
GO
--SUA PHIEU XUAT
CREATE PROC SP_SUAPHIEUXUAT(@ID_PHIEUXUAT INT, @NGAYXUAT DATE)
AS
BEGIN
	UPDATE PHIEUXUATKHO
	SET NGAYXUAT = @NGAYXUAT
	WHERE ID_PHIEUXUATKHO = @ID_PHIEUXUAT
END
GO
--CTPX
--THEM CHI TIET PHIEU XUAT
CREATE PROC SP_THEMCTPX(@ID_CTPX INT,@ID_PHIEUXUATKHO INT ,@ID_SANPHAM INT, @SL INT)
AS
BEGIN
	INSERT INTO CTPX(ID_CTPX,ID_PHIEUXUATKHO ,ID_SANPHAM, SL) VALUES(@ID_CTPX,@ID_PHIEUXUATKHO ,@ID_SANPHAM, @SL)
END
GO
--DSCTPX
CREATE PROC SP_DSCTPX
AS
BEGIN
	SELECT * FROM CTPX
END
GO
--XOA CTPX
CREATE PROC SP_XOACTPX(@ID_CTPX INT)
AS
BEGIN
	DELETE CTPX
	WHERE ID_CTPX = @ID_CTPX
END
GO
--SUA CTPX
CREATE PROC SP_SUACTPX(@ID_CTPX INT, @ID_SANPHAM INT, @SL INT)
AS
BEGIN
	UPDATE CTPX
	SET ID_SANPHAM = @ID_SANPHAM, SL = @SL
	WHERE ID_CTPX = @ID_CTPX
END
GO

--HD
--THEM HOA DON
CREATE PROC SP_THEMHOADON(@ID_HOADON INT, @ID_KHACHHANG INT, @NGAYMUA DATE)
AS
BEGIN
	INSERT INTO HOADON(ID_HOADON, ID_KHACHHANG, NGAYMUA) VALUES(@ID_HOADON, @ID_KHACHHANG, @NGAYMUA)
END
GO
--DSHD
CREATE PROC SP_DSHD
AS
BEGIN
	SELECT * FROM HOADON
END
GO
--XOA HOA DON
CREATE PROC SP_XOAHOADON(@ID_HOADON INT)
AS
BEGIN
	DELETE HOADON WHERE ID_HOADON = @ID_HOADON
END
GO
--SUA HOA DON
CREATE PROC SP_SUAHOADON(@ID_HOADON INT, @ID_KHACHHANG INT, @NGAYMUA DATE)
AS
BEGIN
	UPDATE HOADON
	SET ID_KHACHHANG = @ID_KHACHHANG, NGAYMUA = @NGAYMUA
	WHERE ID_HOADON = @ID_HOADON
END
GO

--CHHD
--THEM CTHD
CREATE PROC SP_THEMCTHD(@ID_CTHD INT, @ID_HOADON INT ,@ID_SANPHAM INT ,@SL INT)
AS
BEGIN
	INSERT INTO CTHD(ID_CTHD, ID_HOADON, ID_SANPHAM, SL) VALUES(@ID_CTHD, @ID_HOADON, @ID_SANPHAM, @SL)
END
GO
--DSHD
CREATE PROC SP_DSCTHD
AS
BEGIN
	SELECT * FROM CTHD
END
GO
--XOA CTHD
CREATE PROC SP_XOACTHD(@ID_CTHD INT)
AS
BEGIN
	DELETE CTHD WHERE ID_CTHD = @ID_CTHD
END
GO
--SUA CTHD
CREATE PROC SP_SUACTHD(@ID_CTHD INT, @ID_SANPHAM INT ,@SL INT)
AS
BEGIN
	UPDATE CTHD
	SET ID_SANPHAM = @ID_SANPHAM, SL = @SL
	WHERE ID_CTHD = @ID_CTHD
END
GO

set dateformat dmy;
--THEM DL

INSERT INTO NGUOIDUNG(ID_NGUOIDUNG, TEN_NGUOIDUNG, DIACHI, SDT, TAIKHOAN, MATKHAU, IS_ADMINISTRATOR) VALUES(1, 'TEN', 'DC', 'SDT', 'admin1', '123456', 'True')
INSERT INTO NGUOIDUNG(ID_NGUOIDUNG, TEN_NGUOIDUNG, DIACHI, SDT, TAIKHOAN, MATKHAU, IS_ADMINISTRATOR) VALUES(2, 'TEN', 'DC', 'SDT', 'nv1', '123456', 'False')

EXEC SP_THEMSANPHAM 1, 'DT1', 'CAI', 250000, 1
EXEC SP_THEMSANPHAM 2, 'DT2', 'CAI', 150000, 2
EXEC SP_THEMSANPHAM 3, 'IPHONE X', 'CAI', 2000000, 2


EXEC SP_THEMPHIEUNHAP 1, '12/2/2018'
EXEC SP_THEMPHIEUNHAP 2, '1/2/2018'

EXEC SP_THEMCTPN 1, 1, 1, 2
EXEC SP_THEMCTPN 2, 1, 3, 3
EXEC SP_THEMCTPN 3, 2, 2, 3
EXEC SP_THEMCTPN 4, 2, 1, 1


EXEC SP_THEMPHIEUXUAT 1, '5/3/2018'
EXEC SP_THEMPHIEUXUAT 2, '4/8/2018'

EXEC SP_THEMCTPX 1, 1, 1, 1
EXEC SP_THEMCTPX 2, 1, 2, 1
EXEC SP_THEMCTPX 3, 2, 1, 1
EXEC SP_THEMCTPX 4, 2, 3, 1


EXEC SP_THEMKHACHHANG 1, 'ABC', 'HCM', '0912345678'
EXEC SP_THEMKHACHHANG 2, 'XYZ', 'HN', '0135792468'


EXEC SP_THEMHOADON 1, 1, '15/12/2018'
EXEC SP_THEMHOADON 2, 2, '12/11/2018'

EXEC SP_THEMCTHD 1, 1, 1, 1
EXEC SP_THEMCTHD 2, 1, 2, 1
EXEC SP_THEMCTHD 3, 2, 3, 2